### PR TITLE
Add lookupSRV function.

### PR DESCRIPTION
**Pull request by jburnham**
Adds support for fetching SRV records and using them in a template. Would go great in conjunction with https://github.com/kelseyhightower/confd/pull/333

### CODE REVIEW

**Comment by kelseyhightower** [comment]
@jburnham Now that #333 has been merged, this will need a rebase. I think we really need to figure out a better way of adding template functions.

**Comment by jburnham** [comment]
Rebased, It looks like the failing test is because of the lookupIP function. TravisCI seems to not have ipv6 so resolving localhost is only 127.0.0.1.

**Comment by kelseyhightower** [comment]
@jburnham Seems there is still a conflict. I fixed a bunch of test so things should be all green now.

**Comment by jburnham** [comment]
Rebased again.

**Comment by kelseyhightower** [comment]
@jburnham Thanks!

**Pull request merged**
