### PR TITLE
Add StackEngine backend support

### PR DESCRIPTION
**Pull request by destari**
Adds simple backend support for StackEngine's built-in kv store.  Uses Authentication Bearer token (auth_token) for API authentication.

### CODE REVIEW

**Comment by bacongobbler** [comment]
Looks good to me. Would you mind adding some setup for StackEngine in [.travis.yml](https://github.com/kelseyhightower/confd/blob/master/.travis.yml) so we can run the tests against this PR? Thanks!

**Comment by destari** [comment]
Hmm, well the API is authenticated and would require a user creation and fetching the auth bearer token to automate that against a live daemon. Thoughts?

**Comment by destari** [comment]
Is this ok to merge?

**Comment by bacongobbler** [comment]
not my call to make :) ping @kelseyhightower for review

**Comment by destari** [comment]
Ping @kelseyhightower :) 
Sorry I missed you at DockerCon!

**Comment by kelseyhightower** [comment]
@destari We need to get some tests in place for this. I'm merging for now, but without updated docs and tests it might get reverted before the next release.

**Comment by destari** [comment]
Ok thanks - when are you planning the next release?

**Pull request merged**
