### PR TITLE
Windows support

### PR DESCRIPTION
**Pull request by HeavyHorst**
I've added support for windows.
This is based on #45.

---

This change is [Reviewable](https://reviewable.io/reviews/kelseyhightower/confd/434)

### CODE REVIEW

**Comment by bacongobbler** [comment]
LGTM, though leaving it to @kelseyhightower for review.

**Comment by syphon7** [comment]
Are there any plans to merge this PR? I would love to start using confd in windows.

**Comment by sasiezilmadhavan** [comment]
Interested in using confd for windows.  Any plans to merge the changes please..?

**Comment by bacongobbler** [comment]
I've gone ahead and made a v0.12.1 release on my fork that includes this change. See [the v0.12.0](https://github.com/bacongobbler/confd/releases/tag/v0.12.0) and [v0.12.1 release notes](https://github.com/bacongobbler/confd/releases/tag/v0.12.1).

**Comment by okushchenko** [comment]
Fixes #453

**Pull request merged**
