### PR TITLE
Proposal feat(go): custom user defined functions as plugins

### PR DESCRIPTION
**Pull request by aledbf**
The idea behind this is to enable custom functions in the `confd` templates without touching the core.

As an example of one plugin  [aledbf/confd-contains-plugin](https://github.com/aledbf/confd-contains-plugin) adds the `strings.Contains` function. In that repository is also a "standard" test that could be required to submit new plugins to `confd`.

With this it could be possible to just fork `confd` and add one/multiple new import/s in `plugins.go` and use new functions.

This PR uses [go-extpoints](https://github.com/progrium/go-extpoints)

### CODE REVIEW

**Comment by mboersma** [comment]
+1

**Comment by kelseyhightower** [comment]
@aledbf This is pretty awesome. Can you rebase so I can test this out?

**Comment by aledbf** [comment]
@kelseyhightower done

**Comment by bacongobbler** [comment]
Now that `strings.Replace` exists in confd, this plugin would have to get updated to reflect that.

Isn't it easier to fork and add your own functions to confd natively? You'd have to fork and register your own plugin inside confd anyways. To me this smells like a little bit of over-engineering

**Pull request closed without merging**
