### PR TITLE
Add base64 encode/decode template helpers

### PR DESCRIPTION
**Pull request by richardmarshall**
Add two new template helper functions, `base64Encode` and `base64Decode`, to enable base64 handling of template data.

### CODE REVIEW

**Comment by bacongobbler** [comment]
LGTM

**Comment by richardmarshall** [comment]
Great, let me know if there's anything else you need from my end.

**Comment by bacongobbler** [comment]
Nothing from your end, just need reviews from Kelsey for any new features. :)

**Comment by richardmarshall** [comment]
Ok, thanks.

**Comment by bacongobbler** [comment]
I've gone ahead and made a v0.12.1 release on my fork that includes this change. See [the v0.12.0](https://github.com/bacongobbler/confd/releases/tag/v0.12.0) and [v0.12.1 release notes](https://github.com/bacongobbler/confd/releases/tag/v0.12.1).

**Pull request merged**
