### PR TITLE
New backend, etcd+crypt

### PR DESCRIPTION
**Pull request by jakexks**
After stumbling across https://github.com/xordataexchange/crypt we thought we should use it, and therefore would need to modify confd to include it!

### CODE REVIEW

**Comment by jakexks** [comment]
Build fails due to the golang crypto library in vendor/src being a subproject from https://github.com/golang/crypto/, wasn't sure whether to include it in the commits or not!

**Comment by bacongobbler** [comment]
isn't this a duplicate of #210?

**Comment by jakexks** [comment]
Ha, didn't notice someone had already done it. It's a slightly different approach though, this blanket decrypts everything on the way out of etcd when you chose the backend "etcdcrypt" rather than adding new template functions to deal with encrypted values, meaning you can use your existing templates unmodified.

**Comment by bacongobbler** [comment]
Personally I'm leaning towards the latter's approach. Working with etcd secrets is probably an edge case for a few certain keys. After that I'd want access to unencrypted values. That's my opinion though. @kelseyhightower?

**Comment by jakexks** [comment]
I agree the method in #210 is definitely more flexible. Our use case is multiple parties configuration being stored in the same etcd cluster, meaning we would blanket encrypt / decrypt with a unique key per party - so it never occurred to me to extend the template parser.

**Comment by kelseyhightower** [comment]
I'm closing this in favor of #210

**Pull request closed without merging**
