### PR TITLE
Add simple redis support

### LINKED ISSUE #168: Add support for Redis as backend
I currently use Redis as a configuration backend in a simple static environment, it would be awesome if confd could add support for using Redis as a backend to create the templates.

### PR DESCRIPTION
**Pull request by cinience**
* watch is not yet supported
* auth and select is not yet support

closes #168

### CODE REVIEW

**Comment by bacongobbler** [comment]
@cinience would you mind rebasing, please? Thanks!

**Comment by cinience** [comment]
Done!

**Comment by bacongobbler** [comment]
sorry, would you mind fixing up your commits? :heart: 

Just one `git reset --hard HEAD^` should remove the top merge commit.

**Comment by cinience** [comment]
sorry, am i right?

**Comment by bacongobbler** [comment]
much better. Thanks! I'll get started testing this either tonight or sometime this weekend. :)

**Comment by bacongobbler** [comment]
Manually tested via the integration tests. The consul service checks fail (of course) but everything else checks out. LGTM!

**Pull request merged**
