### PR TITLE
Feature/add basic arithmetics

### PR DESCRIPTION
**Pull request by corebug**
A rebased version of https://github.com/kelseyhightower/confd/pull/363 by @aquam8.
Original PR looks orphaned.

### CODE REVIEW

**Comment by bacongobbler** [comment]
Just an FYI that this project [is considered unmaintained for the time being](https://github.com/kelseyhightower/confd/issues/460). I'm in communication with kelsey to transfer maintainership to myself or to someone else so this project can carry on, but the original PR is still fine; it's just stale.

**Comment by VitaliiTurovets** [comment]
@bacongobbler sounds pretty sad... Any chance that this, or original PR is going to be merged?

**Comment by bacongobbler** [comment]
eventually, yes. If not you're more than welcome to fork and maintain a separate confd repo. That's the beauty of open source ;)

**Comment by disaster37** [comment]
hi, i need also this PR ;)

**Comment by okushchenko** [comment]
Duplicate of #363

**Pull request closed without merging**
