### PR TITLE
Azuretablestorage

### PR DESCRIPTION
**Pull request by graemechristie**
I've implemented a backend for Azure Table storage.

This is my first time programming in Go, any feedback, constructive or otherwise, is welcome.

### CODE REVIEW

**Comment by graemechristie** [comment]
Probably should have squashed my commits - let me know if this is required and I'll redo the PR.

**Comment by bacongobbler** [comment]
please do. However please keep in mind that this will not likely be merged any time soon; haven't seen activity on this repo for months.

It also looks like you need to add some dependencies to `Godeps` :)

**Comment by graemechristie** [comment]
Also need integration tests - will add these tomorrow

**Comment by graemechristie** [comment]
I'll redo this PR woth squashed commits and integration tests.

Out of interest, why the lack of activity on this repo ? Is there a new hotness we should be using generate configs from kv stores ?

**Pull request closed without merging**
