### PR TITLE
Feature/global slice

### PR DESCRIPTION
**Pull request by wrfly**
Add three functions:
- makeSlice
- appendSlice
- rangeSlice

The slice is global, inspired by <https://stackoverflow.com/questions/36521839/how-to-create-a-global-variable-and-change-in-multiple-places-in-golang-html-tem>

### CODE REVIEW

**Comment by okushchenko** [comment]
Can you share a use case that is being covered by these extra functions?

**Comment by wrfly** [comment]
Hello @okushchenko , actually I did face some problems that `confd` cannot handle by now.
For example, I have a `etcd v3` stores some data:

```
/nodes/online/<hostA>: 1.2.3.4
/nodes/online/<hostB>: 4.5.6.7

/nodes/info/<hostA>/ip : 1.2.3.4
/nodes/info/<hostA>/ports/http: 8080
/nodes/info/<hostA>/ports/grpc: 9090
/nodes/info/<hostB>/ip : 4.5.6.7
/nodes/info/<hostB>/ports/http: 8080
/nodes/info/<hostB>/ports/grpc: 9090
```

And I have an Nginx who wants to proxy these HTTP and grpc ports, the config file should be:

```
upstream http{
  server 1.2.3.4:8080;
  server 4.5.6.7:8080;
}
upstream grpc{
  server 1.2.3.4:9090;
  server 4.5.6.7:9090;
}

server{
  listen 10001;
  proxy_pass http;
}
server{
  listen 10002;
  proxy_pass grpc;
}
```

Without these new funcs, the template file need to range every nodes in each upstream:

```
upstream http{
{{ range gets "/nodes/online/*" -}}
    {{ $hostname := replace .Key "/nodes/online/" "" 1 -}}
    {{ $ip := getv (printf "/nodes/info/%s/ip" $hostname) -}}
    {{ $http := getv (printf "/nodes/info/%s/ports/http" $hostname) -}}
  server {{ printf "%s:%.f;" $ip $http }}
{{end}}
}

upstream grpc{
{{ range gets "/nodes/online/*" -}}
    {{ $hostname := replace .Key "/nodes/online/" "" 1 -}}
    {{ $ip := getv (printf "/nodes/info/%s/ip" $hostname) -}}
    {{ $grpc := getv (printf "/nodes/info/%s/ports/grpc" $hostname) -}}
  server {{ printf "%s:%.f;" $ip $grpc }}
{{end}}
}
```
`confd` have already ranged all the data at first time, it's no need to fetch the data again and again.

I have to admit that the data arranged is not good, it's my fault. But I still think it's good to make `confd` a little complexer than `text/template`.

**Comment by okushchenko** [comment]
Confd does fetching of keys only once per template, so at the moment when a template is being rendered keys were already fetched. I'm against adding any more unnecessary functions or additional complexity without a strong use case behind it.

**Comment by wrfly** [comment]
Yeah, you are right. I didn't know that `confd` feches keys only once and by adding more debug log, I realized it does.

Thus, it's no need to add this function only for "pretty template file".

I'm closing this PR. Thanks.

**Comment by wrfly** [comment]
Hello @okushchenko , I thought I need to reopen this PR because I faced another problem and others may need it.

In my case, I didn't know whether is there a upstream server for:

```
upstream http {
  ???
}
```

And there is no key to check with `{{ if exists "/no/key/to/check" }}`, so the only way to check if there is any upstream server is to range all the keys and check the length of the data fetched:

```
{{ if ne (len (rangeSlice $http)) 0 -}}
upstream http {
{{ range (rangeSlice $http) -}}
    {{ printf "    " }}server {{ . }};
{{ end -}}
}
{{ end }}
```

Besides, better organization of the template is another benefits.

**Comment by hubo1016** [comment]
@wrfly Surely guys in Google are smarter and they have invented a "with" statement
```
{{with pipeline}} T1 {{end}}
	If the value of the pipeline is empty, no output is generated;
	otherwise, dot is set to the value of the pipeline and T1 is
	executed.

{{with pipeline}} T1 {{else}} T0 {{end}}
	If the value of the pipeline is empty, dot is unaffected and T0
	is executed; otherwise, dot is set to the value of the pipeline
	and T1 is executed.
```

So it is
```
{{ with $http -}}
upstream http {
{{ range . -}}
    {{ printf "    " }}server {{ . }};
{{ end -}}
}
{{ end }}
```

**Comment by wrfly** [comment]
@hubo1016 But what is `$http` since I don't know there is any hosts that provides HTTP service... Only `range` can get those keys.

**Comment by hubo1016** [comment]
@wrfly 
```
{{ with gets "/nodes/online/*" -}}
upstream http {
{{ range . -}}
    {{ printf "    " }}server {{ . }};
{{ end -}}
}
{{ end }}
```

`range` is a statement. It is not a function that returns a slice. It is a loop identifier. `gets` returns a slice.

**Comment by hubo1016** [comment]
Another example from my project which is more complicated
```
{{- with lsdir "/discovery/jdb.op.zodiac.storage"}}

storage:
  {{- range . }}
  -
    name: {{ base . }}
    max_file: 1000
    url: http://{{ index (ls (print "/discovery/jdb.op.zodiac.storage/" .)) 0 }}/
    {{- $conf_key := base . | print "/configuration/jdb.op.zodiac.storage/endpoint/" -}}
    {{- if exists (print $conf_key "/redirect_url") }}
    redirect_url: {{getv (print $conf_key "/redirect_url")}}
    {{- end }}
    {{- if exists (print $conf_key "/internal_url") }}
    internal_url: {{getv (print $conf_key "/internal_url")}}
    {{- end }}
    {{- if exists (print $conf_key "/accel-redirect_url") }}
    accel-redirect_url: {{getv (print $conf_key "/accel-redirect_url")}}
    {{- end }}
  {{ end }}
{{- end }}
```

This example uses `lsdir` to iterate into the first level, and `ls` for the second level. It also use `print` to concat keys to create complicated relations.

**Comment by wrfly** [comment]
I'm sorry, I mean I can only `range` those keys to find out whether there is a host that provide an HTTP service. Since there maybe a host online that doesn't provide HTTP service but others.
BTW, `range` can get 'values' too:

```
{{range pipeline}} T1 {{end}}
	The value of the pipeline must be an array, slice, map, or channel.
	If the value of the pipeline has length zero, nothing is output;
	otherwise, dot is set to the successive elements of the array,
	slice, or map and T1 is executed. If the value is a map and the
	keys are of basic type with a defined order ("comparable"), the
	elements will be visited in sorted key order.
```

**Comment by hubo1016** [comment]
@wrfly I see. You have to organize your keys in another way, to make it possible to filter keys with `lsdir` or `gets`. For example, put any HTTP service under `/nodes/info/*/ports/http` and use `with gets "/nodes/info/*/ports/http"`

**Comment by wrfly** [comment]
You are right, the organization of keys have a little problem...
However since I have implemented that design, I need that feature. I can re-organize the keys in next release.

Thanks a lot~

**Pull request closed without merging**
