### PR TITLE
Add Rancher Metadata backend

### PR DESCRIPTION
**Pull request by cloudnautique**
Inside a Rancher Container Service environment a user has access to a container metadata service that is similar to AWS style metadata. With this backend users can consume the data with confd.

This PR has the backend, updated docs, and integration tests. Hopefully I covered everything, but if not let me know and will add whatever is needed.

Thanks!

### CODE REVIEW

**Comment by ibuildthecloud** [comment]
I'll give my completely unbiased +1 :smile:   Who am I kidding, I'm totally biased, but we are having a lot of fun running confd in Rancher, would love to see this merged.

**Comment by antmanler** [comment]
+1

**Comment by clescot** [comment]
+1

**Comment by kelseyhightower** [comment]
LGTM.

**Pull request merged**
