### PR TITLE
Fix broken links to documentation

### PR DESCRIPTION
**Pull request by gautamk**
Move Docs back to root Fixing #296

### CODE REVIEW

**Comment by bacongobbler** [comment]
Let's just move the docs back to the root (https://github.com/kelseyhightower/confd/issues/296#issuecomment-105584908). Thanks for catching this!

**Comment by gautamk** [comment]
@bacongobbler I've updated the pull request to move docs back up to root

**Comment by bacongobbler** [comment]
LGTM

**Comment by superpan** [comment]
thanks.

**Pull request merged**
