### PR TITLE
add --log-level flag

### LINKED ISSUE #32: Improve logging, make it easy to enable/disable debug, warning, and info messages

### PR DESCRIPTION
**Pull request by bacongobbler**
This refactors the log package to use logrus in the background, while
also introducing the `--log-level` flag. This also deprecates flags like
`--quiet`, `--verbose` and `--debug` as all three are covered in one flag.
If a unrecognized log level is introduced, an error is displayed and
`confd` calls `log.Fatal()` with a proper response.

The justification behind switching to logrus allows us in the future to
take advantage of the many features which exist in logrus, such as their
[hook infrastructure](https://github.com/Sirupsen/logrus#hooks).

closes #32

### CODE REVIEW

**Comment by bacongobbler** [comment]
oops, this removes the functionality where WARNING and above get logged to stderr. Lemme fix that :)

**Comment by bacongobbler** [comment]
k, fixed:

```
$ ./bin/confd --log-level debug
2015-04-02T22:02:27-07:00 Matthews-MacBook-Pro-2.local ./bin/confd[18345]: WARNING Skipping confd config file.
2015-04-02T22:02:27-07:00 Matthews-MacBook-Pro-2.local ./bin/confd[18345]: INFO Backend set to etcd
2015-04-02T22:02:27-07:00 Matthews-MacBook-Pro-2.local ./bin/confd[18345]: INFO Starting confd
2015-04-02T22:02:27-07:00 Matthews-MacBook-Pro-2.local ./bin/confd[18345]: INFO Backend nodes set to http://127.0.0.1:4001
2015-04-02T22:02:27-07:00 Matthews-MacBook-Pro-2.local ./bin/confd[18345]: FATAL cannot connect to etcd cluster: http://127.0.0.1:4001
$ ./bin/confd --log-level debug 2>/dev/null
2015-04-02T22:02:21-07:00 Matthews-MacBook-Pro-2.local ./bin/confd[18344]: INFO Backend set to etcd
2015-04-02T22:02:21-07:00 Matthews-MacBook-Pro-2.local ./bin/confd[18344]: INFO Starting confd
2015-04-02T22:02:21-07:00 Matthews-MacBook-Pro-2.local ./bin/confd[18344]: INFO Backend nodes set to http://127.0.0.1:4001
```

**Comment by mboersma** [comment]
:+1: for `--log-level`, looks good.

**Comment by carmstrong** [comment]
Code LGTM. This is much cleaner and easier to understand than having multiple logging flags.

**Pull request merged**
