### PR TITLE
ETCD V3 support

### LINKED ISSUE #536: it does not support etcdctl v3 ?
when i `export ETCDCTL_API=3`
i got errors: `ERROR 100: Key not found (/myapp) [16]`

and i set ETCDCTL_API=2 ，it works

### PR DESCRIPTION
**Pull request by crandles**
Forked from @HeavyHorst #446 
- added an integration test for V3 (and updated v2)
- added basic auth support
- updated godeps

not used to using `godep`, so if I included too many changes let me know.
Started from an empty gopath, used `godep restore`, updated the right repos to get the new etcdv3 API to work and then used `godep save`.

Fixes #536, closes #544

### CODE REVIEW

**Comment by bacongobbler** [comment]
+1 on the etcd v3 integration tests.

**Comment by akaspin** [comment]
Any chances to merge this?

**Comment by crandles** [comment]
While this is waiting, I am going to update the vendored ETCD client. Since this PR the error/failure handling of the client has improved.

**Comment by iwalz** [comment]
Any chance to get this merged? Just waiting to use etcd3 all the way.

**Comment by bacongobbler** [comment]
I've gone ahead and made a v0.12.1 release on my fork that includes this change. See [the v0.12.0](https://github.com/bacongobbler/confd/releases/tag/v0.12.0) and [v0.12.1 release notes](https://github.com/bacongobbler/confd/releases/tag/v0.12.1).

**Comment by brandonto** [comment]
@bacongobbler How likely will confd v0.12.1 on your fork be merged upstream and become an "officially supported" release? We are currently using confd v0.11.0 (don't like the idea of using the alpha releases in production), but the etcdv3 support is very enticing.

**Comment by bacongobbler** [comment]
That depends on Kelsey who is the BDFL for this project. He just hasn't been active for quite some time.

I'll shoot him an email and see if he will pass on maintainer ownership to myself.

**Comment by bacongobbler** [comment]
For the time being you can use the forked version of v0.12.1 and I will continue merging things into the fork as necessary.

**Comment by lucastheisen** [comment]
Thanks @bacongobbler , the [the forked version of v0.12.1](https://github.com/bacongobbler/confd/releases/tag/v0.12.1) works with etcd v3 grpc for [my purposes](https://github.com/kelseyhightower/confd/issues/574)...  Any word on taking ownership of this project, or getting this pull request merged?

**Pull request merged**
