### PR TITLE
Tiny change to enable Windows support

### PR DESCRIPTION
**Pull request by ferreus**
Another version of #434 
This one is just a little change, just allows the windows build, without introducing too much noise.
Let's enjoy confd on Windows ;)

### CODE REVIEW

**Comment by bacongobbler** [comment]
looks like travis didn't enjoy your change:

```
resource/template/stat_posix.go:11: undefined: syscall in syscall.Stat_t
resource/template/stat_posix.go:15: undefined: syscall in syscall.Stat_t
```

**Comment by bacongobbler** [comment]
you'll need to import `syscall` in `stat_posix.go` in order for this to work

**Comment by ferreus** [comment]
Is there's anything i need to do? Or we just waiting for code review?

**Comment by bacongobbler** [comment]
Just waiting for code review from Kelsey.

**Comment by okushchenko** [comment]
Duplicate of #434

**Pull request closed without merging**
