### PR TITLE
*feature) add recursive get toml files.

### PR DESCRIPTION
**Pull request by wuranbo**
Adding recursive find path when find toml file in cond.d.

Cause in our production, company's all project share one conffile project which's master branch is managed only by OP to make the releasing smoothly.I thought it's a very common for Enterprise Software Development.

In this situation, all the files of tens of project in only on directory, make it looks mass. So hope ours can be in part of.

### CODE REVIEW

**Comment by kelseyhightower** [comment]
This looks fine to me. @bacongobbler thoughts on this?

**Comment by kelseyhightower** [comment]
@wuranbo Thanks for the contribution, we should get it reviewed in the next day or so.

**Comment by bacongobbler** [comment]
:+1:

**Comment by wuranbo** [comment]
@kelseyhightower I should thanks your confd project. Help me a lot. O(∩_∩)O~

**Pull request merged**
