### PR TITLE
yaml/json file backend

### LINKED ISSUE #361: Add file based(json and/or yaml) backend
Currently we use confd with the etcd backend for dynamic Nginx configuration.
We want to standardize on confd for all configuration templating.
For some simple one time templating we want to avoid using etcd but rather keep configurations inside a simple json and/or yaml file.

### PR DESCRIPTION
**Pull request by HeavyHorst**
I've createt a simple file based yaml/json backend. Closes #361 

It is working with json files:

```
{
    "MYAPP_DATABASE_URL": "db.example.com",
    "MYAPP_DATABASE_USER": "rob",
}
```

and yaml files:

```

---
  MYAPP_DATABASE_URL: "db.example.com"
  MYAPP_DATABASE_USER: "robby"
```

It has full watch support.
./confd -backend yaml -yaml-file test.yaml -watch

---

This change is [Reviewable](https://reviewable.io/reviews/kelseyhightower/confd/397)

### CODE REVIEW

**Comment by kelseyhightower** [comment]
@HeavyHorst This is a good start. The questions I have are what is the format for the key names. My guess is people will want to use any key name they want. So we should support

```
---
foo: bar
test_foo: bar
```

Maybe we should run this by the person who file the original issue. But so far so good.

**Comment by kelseyhightower** [comment]
@HeavyHorst I'll be able to take a deeper review later this evening, but so far the use of fsnotify feels right.

**Comment by HeavyHorst** [comment]
@kelseyhightower it should now be possible to choose any key name.

**Comment by elsonrodriguez** [comment]
Looking good, works as advertised and provides an extremely light way for people to store data.

#### Cosmetic issue:

```
2016-02-24T20:12:11-08:00 ireul.local bin/confd[13853]: INFO Backend set to yaml
2016-02-24T20:12:11-08:00 ireul.local bin/confd[13853]: INFO Starting confd
2016-02-24T20:12:11-08:00 ireul.local bin/confd[13853]: INFO Backend nodes set to 
```

Would it be possible to change the text "Backend nodes set to" to "Backend source(s) set to", and to put the path of the json/yaml file afterwards?

#### User Experience:
It looks like you can pass in a JSON or YAML file, but the command line makes it seem like it only takes YAML. What do you think of changing the backend name to something like "file", and `-yaml-file` argument to `-file`?


#### Other Stuff:
I was only able to get flat data to work, deep structures ended up with this:
```
2016-02-24T20:45:00-08:00 ireul.local bin/confd[14332]: ERROR yaml: unmarshal errors:
  line 2: cannot unmarshal !!map into string
```

I used this the data.
```
---
myapp:
  database:
    url: url1
    user: user1
```
This might be fine if it's the desired behavior, since using multiple files can approximate the functionality. Downside is that it will require that all templates/configs be changed to remove nested data.

**Comment by bacongobbler** [comment]
That is a limitation. For example in our use case we use etcd like so:

```
/deis/database/hosts/192.168.0.1
/deis/database/hosts/192.168.0.2
/deis/database/hosts/192.168.0.3
/deis/database/hosts/192.168.0.4
```

So if it was in file form I'd imagine it to work something like

```
deis:
  database:
    hosts:
      - 192.168.0.1
      - 192.168.0.2
      - 192.168.0.3
      - 192.168.0.4
```

To replicate the same behaviour.

**Comment by bacongobbler** [comment]
Would you also mind adding integration tests inside `integration/file` as well so we can validate this? Thanks!

**Comment by HeavyHorst** [comment]
test file:
```
deis:
  database:
    hosts:
      - 192.168.0.1: test1
      - 192.168.0.2
      - 192.168.0.3
      - 192.168.0.4

myapp:
  database: {url: www.google.de, user: Boris}
```
```
Map: map[string]string{"/myapp/database/url":"www.google.de", "/myapp/database/user":"Boris", "/deis/database/hosts/192.168.0.1":"test1", "/deis/database/hosts/192.168.0.2":"", "/deis/database/hosts/192.168.0.3":"", "/deis/database/hosts/192.168.0.4":""}
```
I will add the integration tests soon.

thanks for the feedback !

**Comment by bacongobbler** [comment]
LGTM! Awesome work. :)

**Comment by elsonrodriguez** [comment]
LGTM, Rockin!

**Comment by urlund** [comment]
+1 (when is next release, and is this included?)

**Comment by crossell** [comment]
@kelseyhightower Thank you for creating confd, I'm working on a project where this is exactly the tool we needed.

@HeavyHorst +1

When will this be merged / released in next stable version? Looking to use this feature.

**Comment by bechtoldt** [comment]
Looking forward to see this in upstream!

**Comment by bechtoldt** [comment]
@kelseyhightower is this PR ready to merge?

/cc @HeavyHorst

**Comment by bacongobbler** [comment]
I've gone ahead and made a v0.12.1 release on my fork that includes this change. See [the v0.12.0](https://github.com/bacongobbler/confd/releases/tag/v0.12.0) and [v0.12.1 release notes](https://github.com/bacongobbler/confd/releases/tag/v0.12.1).

**Comment by hubo1016** [comment]
This should be fixed and merged

**Pull request merged**
