### PR TITLE
optional authentication (via client-key) support for redis

### PR DESCRIPTION
**Pull request by israelchen**
Hi,

Just thought you might be interested.

I've added support for authentication to redis via the client-key argument.
This is optional and if client-key is not set it'll still work provided that redis does not require authentication of course.

--Israel

### CODE REVIEW

**Comment by israelchen** [comment]
This i think resolves #317 - Redis backend AUTH support

**Comment by ericbarch** [comment]
Any reason why this one hasn't been merged in? Currently building israelchen's branch myself as it works beautifully.

**Comment by bacongobbler** [comment]
the PR needs a rebase before we can merge this.

**Comment by kelseyhightower** [comment]
@ericbarch @bacongobbler The other PR was merged, closing this one.

**Pull request closed without merging**
