### PR TITLE
Update file backend to support multiple files

### PR DESCRIPTION
**Pull request by lucastheisen**
Update the `file` backend to leverage [clconf](https://github.com/pastdev/clconf) which adds support for multiple files.

This pull request supercedes _Add clconf backend #663_ based upon recommendations from @okushchenko including:

* rewrite clconf backend as a replacement for the current file backend
* keep in mind that it will have to be compatible with both json and yaml files
* support for multiple files in the file backend

### CODE REVIEW

**Comment by lucastheisen** [comment]
@okushchenko , I have tried a couple of times to get the CI to build successfully, however both `test` and `integration` fail:
```
$ make test
Running tests...
open /tmp/go-build065041852/b231/vet.cfg: no such file or directory
open /tmp/go-build065041852/b232/vet.cfg: no such file or directory
open /tmp/go-build065041852/b235/vet.cfg: no such file or directory
open /tmp/go-build065041852/b237/vet.cfg: no such file or directory
open /tmp/go-build065041852/b257/vet.cfg: no such file or directory
open /tmp/go-build065041852/b047/vet.cfg: no such file or directory
go build github.com/kelseyhightower/confd/resource/template (testmain): open /tmp/go-build065041852/b267/importcfg: no such file or directory
open /tmp/go-build065041852/b001/confd.test: no such file or directory
FAIL	github.com/kelseyhightower/confd [build failed]
?   	github.com/kelseyhightower/confd/backends	[no test files]
?   	github.com/kelseyhightower/confd/backends/consul	[no test files]
?   	github.com/kelseyhightower/confd/backends/dynamodb	[no test files]
?   	github.com/kelseyhightower/confd/backends/env	[no test files]
?   	github.com/kelseyhightower/confd/backends/etcd	[no test files]
?   	github.com/kelseyhightower/confd/backends/etcdv3	[no test files]
ok  	github.com/kelseyhightower/confd/backends/file	0.069s
FAIL	github.com/kelseyhightower/confd/resource/template [build failed]
make: *** [test] Error 1
The command "make test" exited with 2.


$ make integration
Running integration tests...
Running ./integration/zookeeper/test.sh
2018/02/24 19:54:19 Connected to 127.0.0.1:2181
2018/02/24 19:54:19 Authentication failed: EOF
panic: zk: could not connect to a server
goroutine 1 [running]:
main.check(0x5868c0, 0xc4200883f0)
	/home/travis/gopath/src/github.com/kelseyhightower/confd/integration/zookeeper/main.go:15 +0x4a
main.zk_write(0xc42009e3e4, 0x7, 0x0, 0x0, 0xc4200ca2c0)
	/home/travis/gopath/src/github.com/kelseyhightower/confd/integration/zookeeper/main.go:21 +0x88
main.parsejson(0xc42009e3e4, 0x7, 0x53eda0, 0xc42008a840, 0xc4200ca2c0)
	/home/travis/gopath/src/github.com/kelseyhightower/confd/integration/zookeeper/main.go:39 +0x4df
main.parsejson(0x0, 0x0, 0x53eda0, 0xc42008a720, 0xc4200ca2c0)
	/home/travis/gopath/src/github.com/kelseyhightower/confd/integration/zookeeper/main.go:41 +0x44e
main.main()
	/home/travis/gopath/src/github.com/kelseyhightower/confd/integration/zookeeper/main.go:63 +0x191
exit status 2
2018-02-24T19:54:19Z travis-job-e6f5f019-3596-41c8-8dc7-c3af500f9b66 confd[5533]: INFO Backend set to zookeeper
2018-02-24T19:54:19Z travis-job-e6f5f019-3596-41c8-8dc7-c3af500f9b66 confd[5533]: INFO Starting confd
2018-02-24T19:54:19Z travis-job-e6f5f019-3596-41c8-8dc7-c3af500f9b66 confd[5533]: INFO Backend source(s) set to 127.0.0.1:2181
2018-02-24T19:54:19Z travis-job-e6f5f019-3596-41c8-8dc7-c3af500f9b66 confd[5533]: DEBUG Loading template resources from confdir ./integration/confdir
2018/02/24 19:54:19 Failed to connect to 127.0.0.1:2181: dial tcp 127.0.0.1:2181: connect: connection refused
2018-02-24T19:54:19Z travis-job-e6f5f019-3596-41c8-8dc7-c3af500f9b66 confd[5533]: DEBUG Found template: integration/confdir/conf.d/basic.toml
2018-02-24T19:54:19Z travis-job-e6f5f019-3596-41c8-8dc7-c3af500f9b66 confd[5533]: DEBUG Loading template resource from integration/confdir/conf.d/basic.toml
2018-02-24T19:54:19Z travis-job-e6f5f019-3596-41c8-8dc7-c3af500f9b66 confd[5533]: DEBUG Found template: integration/confdir/conf.d/exists.toml
2018-02-24T19:54:19Z travis-job-e6f5f019-3596-41c8-8dc7-c3af500f9b66 confd[5533]: DEBUG Loading template resource from integration/confdir/conf.d/exists.toml
2018-02-24T19:54:19Z travis-job-e6f5f019-3596-41c8-8dc7-c3af500f9b66 confd[5533]: DEBUG Found template: integration/confdir/conf.d/iteration.toml
2018-02-24T19:54:19Z travis-job-e6f5f019-3596-41c8-8dc7-c3af500f9b66 confd[5533]: DEBUG Loading template resource from integration/confdir/conf.d/iteration.toml
2018-02-24T19:54:19Z travis-job-e6f5f019-3596-41c8-8dc7-c3af500f9b66 confd[5533]: DEBUG Found template: integration/confdir/conf.d/nested.toml
2018-02-24T19:54:19Z travis-job-e6f5f019-3596-41c8-8dc7-c3af500f9b66 confd[5533]: DEBUG Loading template resource from integration/confdir/conf.d/nested.toml
2018-02-24T19:54:19Z travis-job-e6f5f019-3596-41c8-8dc7-c3af500f9b66 confd[5533]: DEBUG Retrieving keys from store
2018-02-24T19:54:19Z travis-job-e6f5f019-3596-41c8-8dc7-c3af500f9b66 confd[5533]: DEBUG Key prefix set to /
2018/02/24 19:54:20 Failed to connect to 127.0.0.1:2181: dial tcp 127.0.0.1:2181: connect: connection refused
2018-02-24T19:54:20Z travis-job-e6f5f019-3596-41c8-8dc7-c3af500f9b66 confd[5533]: ERROR zk: could not connect to a server
2018-02-24T19:54:20Z travis-job-e6f5f019-3596-41c8-8dc7-c3af500f9b66 confd[5533]: DEBUG Retrieving keys from store
2018-02-24T19:54:20Z travis-job-e6f5f019-3596-41c8-8dc7-c3af500f9b66 confd[5533]: DEBUG Key prefix set to /
2018/02/24 19:54:21 Failed to connect to 127.0.0.1:2181: dial tcp 127.0.0.1:2181: connect: connection refused
2018-02-24T19:54:21Z travis-job-e6f5f019-3596-41c8-8dc7-c3af500f9b66 confd[5533]: ERROR zk: could not connect to a server
2018-02-24T19:54:21Z travis-job-e6f5f019-3596-41c8-8dc7-c3af500f9b66 confd[5533]: DEBUG Retrieving keys from store
2018-02-24T19:54:21Z travis-job-e6f5f019-3596-41c8-8dc7-c3af500f9b66 confd[5533]: DEBUG Key prefix set to /
2018/02/24 19:54:22 Failed to connect to 127.0.0.1:2181: dial tcp 127.0.0.1:2181: connect: connection refused
2018-02-24T19:54:22Z travis-job-e6f5f019-3596-41c8-8dc7-c3af500f9b66 confd[5533]: ERROR zk: could not connect to a server
2018-02-24T19:54:22Z travis-job-e6f5f019-3596-41c8-8dc7-c3af500f9b66 confd[5533]: DEBUG Retrieving keys from store
2018-02-24T19:54:22Z travis-job-e6f5f019-3596-41c8-8dc7-c3af500f9b66 confd[5533]: DEBUG Key prefix set to /
2018/02/24 19:54:23 Failed to connect to 127.0.0.1:2181: dial tcp 127.0.0.1:2181: connect: connection refused
2018-02-24T19:54:23Z travis-job-e6f5f019-3596-41c8-8dc7-c3af500f9b66 confd[5533]: ERROR zk: could not connect to a server
2018-02-24T19:54:23Z travis-job-e6f5f019-3596-41c8-8dc7-c3af500f9b66 confd[5533]: FATAL zk: could not connect to a server
make: *** [integration] Error 1
The command "make integration" exited with 2.
```
Is there something I am missing?  Or does the CI need to be run differently for it to succeed?

**Comment by okushchenko** [comment]
@lucastheisen it might be caused by the way CI treats temporary directories or files you create in tests.

Also, whats the purpose of `--file-base64` option?

**Comment by lucastheisen** [comment]
@okushchenko , I will try tinkering with temp files from tests I added, but the errors in the CI indicate something to do with zookeeper which i didn't touch...  I'll see what I can figure out.  In the meantime, can you confirm that the CI works for you?  Does it work off of a fork you are working in, or do you only ever use the CI in the main project?

The `--file-base64` option is to allow you to encode a _file_ contents as a base64 string.  We have found this really handy when working with docker.  Its rather easy to pass a string in as a variable when starting a container.  With the `--file-base64` option, that string can be treated as if it were a file, and thus merged with the rest of the config files before being used in the templates.  This way we can build the image with a built in config file like:
```
database:
  url: "jdbc:mysql://db.cluster.local:3306/mydb"
  driver: com.mysql.jdbc.Driver
  username: default
  password: default
```
Then when we start a container from that image we can pass in a base64 encoded version of (as environment variable, ex: `docker run -e "SECRETS_BASE64=..." myapp`):
```
database:
  username: real_user
  password: real_password
```
And have our startup scripts use `confd` like this:
```
confd -onetime \
    -backend file \
    -file /etc/myapp/config.yml \
    -file-base64 $SECRETS_BASE64 \
    -confdir /etc/myapp/confd
```

**Comment by lucastheisen** [comment]
@okushchenko, Another thing of note, I had to add:
```
# this allows forked projects to be buildt by travis before submitting pull reqs...
go_import_path: github.com/kelseyhightower/confd
```
to the `.travis.yml` in order to allow my own travis instance to build...  Should I submit a separate pull request for that, or just leave it in this one?

**Comment by okushchenko** [comment]
@lucastheisen adding a `go_import_path` is a great idea, you can leave it as a part of this PR.
The latest build in master was 3 days ago and all green - https://travis-ci.org/kelseyhightower/confd/builds/345591079
Thanks for explaining the `--file-base64` option, it would be really nice to add an example in the docs. Looks like a good feature to have around. On the other hand, it could be replaced with a simple
```sh
echo $SECRETS_BASE64 | base64 -d > /etc/myapp/secrets.yml
confd -onetime \
    -backend file \
    -file /etc/myapp/config.yml,/etc/myapp/secrets.yml \
    -confdir /etc/myapp/confd
```
you can even write to a tmpfs volume if you don't want your secrets to touch the disk. What do you think?

**Comment by lucastheisen** [comment]
@okushchenko , i figured out my build problem (as you can see from the [latest build](https://travis-ci.org/kelseyhightower/confd/builds/347061933?utm_source=github_status&utm_medium=notification)).  Turns out i was trying to remove the tempdir (`/tmp`) at the end of the unit tests, whoops.  Anyway, this new updated `file` backend is ready, with full backwards compatibility and the multi-file feature.

> Thanks for explaining the `--file-base64` option, it would be really nice to add an example in the docs.

Done.  That said, the docs are quite lite on the information for each backend.  I tried to keep the documentation for `file` (which wasn't there to start with) in line with the rest.  So I didn't go into much detail.  I could add more, but it would certainly seem out of place considering the rest of the docs.

> On the other hand, it could be replaced with a simple...

Yup, it could be, but this is built in to `clconf`, so supporting it here was just a matter of adding a single additional command line option and make the usage (in my opinion) much simpler:
```
confd -onetime \
    -backend file \
    -file /etc/myapp/config.yml,/etc/myapp/secrets.yml \
    -file-base64 $OVERRIDES \
    -confdir /etc/myapp/confd
```
And no need for additional files.  I can remove it if you are against it, but it is very useful to my team.

**Comment by lucastheisen** [comment]
@okushchenko , if you plan on merging this pull request in, I will integrate the patch from #686 which resolves #667.  This will resolve #640 too.

**Comment by okushchenko** [comment]
@lucastheisen I think about merging #686 as a replacement for your PR.

1. It adds no new dependencies and is much simpler.
2. It can perform a recursive lookup for all files in a given directory.
3. It doesn't have the `--file-base64` option, which I consider redundant.

What do you think?

**Comment by lucastheisen** [comment]
@okushchenko , fair enough.  My team actually relies on more of the features provided by `clconf` (the ability to obtain the `-file` and `-file-base64` options from environment variables), so I guess we will work off of our fork until [Plugin system](https://github.com/kelseyhightower/confd/pull/568) or something like [Any suggestions on how to use confd as library](https://github.com/kelseyhightower/confd/issues/632).  Go ahead and close this pull request.

**Pull request closed without merging**
